version: '3.8'
services:
  rabbitmq-lab:
    container_name: rabbitmq-lab
    image: rabbitmq:3.7-management
    ports:
    - 15672:15672
    - 5672:5672
    # volumes:
    #   - ./cert:/etc/rabbitmq/cert 